import { Inter, JetBrains_Mono } from "next/font/google";
import Head from "next/head";
import Navbar from "./navbar";

const sans = Inter({ subsets: ["latin"], variable: "--font-sans" });
const mono = JetBrains_Mono({
  subsets: ["latin"],
  variable: "--font-mono",
});

interface LayoutProps {
  children: React.ReactNode;
}

const Layout: React.FC<LayoutProps> = ({ children }) => {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className={`${sans.variable} ${mono.variable} flex h-screen w-screen flex-col font-sans`}
      >
        <Navbar />
        {children}
      </div>
    </>
  );
};
export default Layout;
